device:
  user1: root

include:
  file: trixie-minbase.yaml

image:
  boot_part_size: 200%
  root_part_size: 300%
  name: dart_os

layer:
  device: dart-device
  software: dart-software
  splash: rpi-splash-screen
  dhcp: dhcp-server
  ssh: openssh-server
  rrp: rpi-root-password

zre_cantools:
  path: ./src/zre_cantools/

rpi_root:
  password: zre

ssh:
  pubkey_user1: ./keys/id_rsa.pub

splash:
  image_path: ${@SRCROOT}/splash.tga