device:
  # The default username and password of the system. Normally a plaintext password would be a security concern, however the
  # DART is isolated from the Internet and the password is meant to be common knowledge.
  # Also note there are security requirements preventing this password being any simpler.
  user1: zre
  user1pass: Zips2026!

include:
  file: trixie-minbase.yaml

image:
  boot_part_size: 200%
  root_part_size: 300%
  name: dart_os

layer:
  device: dart-device
  software: dart-software
  splash: rpi-splash-screen
  dhcp: dhcp-server
  ssh: openssh-server

zre_cantools:
  path: ./src/zre_cantools/

ssh:
  pubkey_user1: ./keys/id_rsa.pub

splash:
  image_path: ${@SRCROOT}/splash.tga